### ISSUE TITLE
create a zoltar option in connect_hub()

### ISSUE THREAD

**Issue by nickreich** [Infectious-Disease-Modeling-Hubs/hubData#10]
For starters, I'm hoping that @matthewcornell can help scope out what would be needed here and implement it. There may be some needed changes in the Zoltar system as well to make this work. @annakrystalli do you have any thoughts about what important things to think about here would be, or what hurdles we may face in doing this?

**Comment by matthewcornell** [comment]
Please review [this Google doc](https://docs.google.com/document/d/1ohfcTzGil6A4Ew2aczWENgUlGR6UgRUjan-GovrwS2U/edit), which is my take on a specification for this issue. In it I summarize my understanding of the problem and identify some questions. @annakrystalli : Please let me know if you have permissions issues.

**Comment by matthewcornell** [comment]
Thanks for the helpful comments! I've edited the google doc to reflect them, and I think it's ready to go.

**Comment by matthewcornell** [comment]
I saw Melissa's email **Release of schema version v3.0.0 and breaking changes to hubverse packages** , which has a link to [Notes on the sample output_type](https://docs.google.com/document/d/1vJT8Uw8fQgoY5sajcokZSfnF7M89eiiiwlRXVkCuj2k/edit#heading=h.40zobtuckjnu) document. Question: How do these changes affect this issue?

**Comment by matthewcornell** [comment]
Possible future issue/question: Do we plan on supporting querying zoltar truth data in addition to forecast data?

**Comment by matthewcornell** [comment]
Question re: converting zoltar target names to hub `horizon` and `target`: Zoltar has target meta information like the following:

```json
{
    "id": 2032,
    "url": "https://zoltardata.com/api/target/2032/",
    "name": "17 day ahead inc hosp",
    "type": "continuous",
    "description": "Zero- to one-hundred-thirty-day ahead forecasts will be defined as the number of incident hospitalizations for the target day.",
    "outcome_variable": "incident hospitalizations",
    "is_step_ahead": true,
    "numeric_horizon": 17,
    "reference_date_type": "DAY",
    "cats": []
}
```

We see two ways to transform this into hub model output format:
1. Start with `name`, remove `numeric_horizon` from it, leading to: `horizon`="17", `target`="day ahead inc hosp".
2. Ignore `name` and instead combine `reference_date_type` and `outcome_variable`, leading to: horizon`="17" (same conversion as (1), `target`="DAY ahead incident hospitalizations", where " ahead " is added by the conversion.

We think bullet (1) might be better for cases where " ahead " is confusing for certain hubs. Also, (1) would preserve abbreviation conventions.

**Comment by annakrystalli** [comment]
I vote for option 1!

**Comment by annakrystalli** [comment]
> Possible future issue/question: Do we plan on supporting querying zoltar truth data in addition to forecast data?

I'll leave this one for @nickreich as I'm not sure
> I saw Melissa's email Release of schema version v3.0.0 and breaking changes to hubverse packages , which has a link to [Notes on the sample output_type](https://docs.google.com/document/d/1vJT8Uw8fQgoY5sajcokZSfnF7M89eiiiwlRXVkCuj2k/edit#heading=h.40zobtuckjnu) document. Question: How do these changes affect this issue?

> I don't _think_ this affects zoltar at all as the actual model output data is stored in the same format as other output types. It primarily affects the config and any functions that use the config to validate model output data

**Comment by nickreich** [comment]
Consolidating responses to above questions in one comment here:

> Possible future issue/question: Do we plan on supporting querying zoltar truth data in addition to forecast data?

I think it could make sense to do this at some point. e.g. query "Zoltar truth data" and return "Hubverse target data" in one of the specified formats.

> I saw Melissa's email Release of schema version v3.0.0 and breaking changes to hubverse packages , which has a link to [Notes on the sample output_type](https://docs.google.com/document/d/1vJT8Uw8fQgoY5sajcokZSfnF7M89eiiiwlRXVkCuj2k/edit#heading=h.40zobtuckjnu) document. Question: How do these changes affect this issue?

IIRC, Zoltar stores an implicit "sample id" in that the ordering of samples implies a simple index that is assumed to be the same (e.g. numbers 1 through 100 for 100 samples) for each prediction (zoltar term) or "individual modeling task" (hubverse term). But no actual sample index (equivalent to the hubverse `output_type_id`) is stored in Zoltar. So I don't think that the schema changes really impact this issue directly. But in my mind the larger question is how will the `output_type_id` column be populated in any data that are returned? Maybe just with this implied index, returned as sequential integers,  for each individual modeling task?

> Question re: converting zoltar target names to hub `horizon` and `target` ...
I agree with above comments supporting option 1.
