### ISSUE TITLE
On calling `connect_hub`, default `arrow` install yields `Error: This build of the arrow package does not support Datasets`

### ISSUE THREAD

**Issue by elray1** [Infectious-Disease-Modeling-Hubs/hubData#15]
Since upgrading to R 4.3.3 on Mac OS "Sonoma", I have noted that with a default installation of the `arrow` package, a call to `connect_hub` yields the following error:

```
Error: This build of the arrow package does not support Datasets
```

I have been able to correct this by installing the `arrow` package from source. Using `renv`, I used the following command:
```
renv::install("arrow", type = "source", rebuild = TRUE)
```

I'm not sure if this is specific to my setup somehow? If not, maybe it would be helpful to add a note about this somewhere -- perhaps to the readme?

**Comment by LucieContamin** [comment]
I don't know if it's correct place to add that, but depending on your system/installation you might also have some issue with some compression. So I agree, it might be good to emphasize the required `arrow` setup in the README

**Comment by annakrystalli** [comment]
Sure. That's a good idea. In the meantime I noticed the following posted to the rOpenSci slack arrow channel:
> Just an FYI for arrow R users on Macs, the team is aware that the 15.0.1 version on CRAN is missing most of its features and we're working on a new submission.
> There are a few alternatives for installing arrow on a Mac but maybe the easiest is to install from R-universe: https://apache.r-universe.dev/arrow.

**Comment by annakrystalli** [comment]
This fixed it for me: 
```r
install.packages("arrow", repos = c("https://apache.r-universe.dev", "https://cran.r-project.org"))
```

**Comment by annakrystalli** [comment]
I imagine this particular issue is a result of the problem with the last CRAN release but given arrow can be temperamental I think it's indeed a good idea to do some signposting to help in the README
